#Generated by HackerRank
#!/bin/python3
import math
import os
import random
import re
import sys


# Created by me
def hourglassSum(arr):
    biggest = -9 * 7 #given largest value of an hourglass   
    for i in range(0, len(arr) - 2):
        for j in range(0, len(arr[0]) - 2):
            t1 = arr[i][j]
            t2 = arr[i][j+1]
            t3 = arr[i][j+2]
            m = arr[i+1][j+1]
            b1 = arr[i+2][j]
            b2 = arr[i+2][j+1]
            b3 = arr[i+2][j+2]
            summed = t1 + t2 + t3 + m + b1 + b2 + b3
            biggest = max(biggest, summed) 
    return(biggest)


#Generated by HackerRank
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
