### Function Description

Complete the minimumAbsoluteDifference function in the editor below. It should return an integer that represents the minimum absolute difference between any pair of elements.

minimumAbsoluteDifference has the following parameter(s):

n: an integer that represents the length of arr
arr: an array of integers
###

#Generated by HackerRank
#!/bin/python3

import math
import os
import random
import re
import sys

# Created by me
def minimumAbsoluteDifference(arr):
    arr.sort()
    total = arr[len(arr)-1] - arr[0]
    for x in range(len(arr)-1):
        i = arr[x+1] - arr[x]
        total = min(i, total)
    return total    
    
    
#Generated by HackerRank    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = minimumAbsoluteDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
